INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (1, 'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-1.jpg', 'Black & White Marble', 65, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (2, 'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-2.jpg', 'Black & Orange Marble', 60, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (3, 'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-3.jpg', 'White Granite', 70, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (4, 'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-4.jpg', 'Blue Granite', 70, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (5, 'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-5.jpg', 'White & Light Gray Marble', 65, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (6, 'Material: Quartz Stone', '/assets/images/wrist-rests/wrist-rest-6.jpg', 'Black & White Quartz', 60, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (7, 'Material: Quartz Stone', '/assets/images/wrist-rests/wrist-rest-7.jpg', 'Black & White Quartz', 60, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (8, 'Material: Epoxy Resin', '/assets/images/wrist-rests/wrist-rest-8.jpg', 'Coral-Blue Resin', 60, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (9, 'Material: Epoxy Resin', '/assets/images/wrist-rests/wrist-rest-9.jpg', 'White-Pearl Resin', 60, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (10,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-10.jpg', 'Coral-Green Marble', 60, 1);

INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (11,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-1.jpg', 'V2 Black & White Marble', 80, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (12,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-2.jpg', 'V2 Black & Orange Marble', 80, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (13,  'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-3.jpg', 'V2 White Granite', 100, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (14,  'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-4.jpg', 'V2 Blue Granite', 110, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (15,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-5.jpg', 'V2 White & Light Gray Marble', 95, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (16,  'Material: Quartz Stone', '/assets/images/wrist-rests/wrist-rest-6.jpg', 'V2 Black & White Quartz', 90, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (17,  'Material: Quartz Stone', '/assets/images/wrist-rests/wrist-rest-7.jpg', 'V2 Black & White Quartz', 90, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (18,  'Material: Epoxy Resin', '/assets/images/wrist-rests/wrist-rest-8.jpg', 'V2 Coral-Blue Resin', 50, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (19,  'Material: Epoxy Resin', '/assets/images/wrist-rests/wrist-rest-9.jpg', 'V2 White-Pearl Resin', 68, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (20,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-10.jpg', 'V2 Coral-Green Marble', 100, 1);

INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (21,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-1.jpg', 'V3 Black & White Marble', 70, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (22,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-2.jpg', 'V3 Black & Orange Marble', 70, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (23,  'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-3.jpg', 'V3 White Granite', 70, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (24,  'Material: Granite Stone', '/assets/images/wrist-rests/wrist-rest-4.jpg', 'V3 Blue Granite', 80, 1);
INSERT INTO store.products (id, description, image_url, name, price, quantity) VALUES (25,  'Material: Marble Stone', '/assets/images/wrist-rests/wrist-rest-5.jpg', 'V3 White & Light Gray Marble', 85, 1);



# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (1, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-1.jpg', 'Black & White Marble', 65, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (2, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-2.jpg', 'Black & Orange Marble', 60, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (3, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-3.jpg', 'White Granite', 70, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (4, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-4.jpg', 'Blue Granite', 70, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (5, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-5.jpg', 'White & Light Gray Marble', 65, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (6, null, 'Material: Quartz Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-6.jpg', 'Black & White Quartz', 60, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (7, null, 'Material: Quartz Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-7.jpg', 'Black & White Quartz', 60, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (8, null, 'Material: Epoxy Resin', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-8.jpg', 'Coral-Blue Resin', 60, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (9, null, 'Material: Epoxy Resin', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-9.jpg', 'White-Pearl Resin', 60, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (10, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-10.jpg', 'Coral-Green Marble', 60, 1, null, null, null, null);
#
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (11, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-1.jpg', 'V2 Black & White Marble', 80, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (12, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-2.jpg', 'V2 Black & Orange Marble', 80, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (13, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-3.jpg', 'V2 White Granite', 100, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (14, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-4.jpg', 'V2 Blue Granite', 110, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (15, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-5.jpg', 'V2 White & Light Gray Marble', 95, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (16, null, 'Material: Quartz Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-6.jpg', 'V2 Black & White Quartz', 90, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (17, null, 'Material: Quartz Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-7.jpg', 'V2 Black & White Quartz', 90, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (18, null, 'Material: Epoxy Resin', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-8.jpg', 'V2 Coral-Blue Resin', 50, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (19, null, 'Material: Epoxy Resin', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-9.jpg', 'V2 White-Pearl Resin', 68, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (20, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-10.jpg', 'V2 Coral-Green Marble', 100, 1, null, null, null, null);
#
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (21, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-1.jpg', 'V3 Black & White Marble', 70, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (22, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-2.jpg', 'V3 Black & Orange Marble', 70, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (23, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-3.jpg', 'V3 White Granite', 70, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (24, null, 'Material: Granite Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-4.jpg', 'V3 Blue Granite', 80, 1, null, null, null, null);
# INSERT INTO store.products (id, active, description, discount, discount_description, discount_price, discount_type, image_url, name, price, quantity, summary, units_in_stock, weight, category_id) VALUES (25, null, 'Material: Marble Stone', null, null, null, null, '/assets/images/wrist-rests/wrist-rest-5.jpg', 'V3 White & Light Gray Marble', 85, 1, null, null, null, null);
